version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kcs-portal-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./database:/usr/src/app/database
      - ./logs:/usr/src/app/logs
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
      - HOST=${HOST}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kcs-portal-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - ./.env
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${HOST}
    depends_on:
      - backend