version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kcs-portal-backend
    ports:
      - "3000:3000"
    volumes:
      - ./database:/usr/src/app/database
      - ./logs:/usr/src/app/logs
    env_file:
      - ./backend/.env
    environment:
      # Ensure NODE_ENV is production if not set in env file
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kcs-portal-frontend
    ports:
      - "5173:4173"
    depends_on:
      - backend 