version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kcs-portal-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./database:/usr/src/app/database
      - ./logs:/usr/src/app/logs
      # Optional accounts list; mount at container root so seed script can find it
      - ./accounts_list.md:/usr/src/accounts_list.md:ro
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
      - HOST=${HOST}
    # Check for accounts_list.md; seed DB if present, otherwise skip
    command: >
      sh -c "if [ -f /usr/src/accounts_list.md ]; then echo 'Found accounts_list.md, seeding DB...' && npm run seed:prod; else echo 'No accounts_list.md found, skipping DB seed'; fi && node dist/server.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kcs-portal-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - ./.env
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${HOST}
    depends_on:
      - backend