version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kcs-portal-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./database:/usr/src/app/database
      - ./logs:/usr/src/app/logs
      # Optional accounts list, will trigger seeding if present
      - ./accounts_list.md:/usr/src/app/accounts_list.md:ro
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
      - HOST=${HOST}
    # If accounts_list.md is mounted, seed the DB before starting
    command: >
      sh -c "if [ -f /usr/src/app/accounts_list.md ]; then npm run seed:prod; fi && node dist/server.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kcs-portal-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - ./.env
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${HOST}
    depends_on:
      - backend